<a href="https://colab.research.google.com/github/shubhamByte/Machine-Learning/blob/main/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing

# Scaling without saving the parameters

In [5]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Does scaling such that mean of train data is 0 and variance of train data is 1. But you didn't save the parameters to scale the test data before feeding the model.(disadvantage)

In [3]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [7]:
X_scaled.mean(axis = 0), X_scaled.std(axis = 0)

(array([0., 0., 0.]), array([1., 1., 1.]))

# Scaling and saving the Parameters

In [9]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

# parameters saved in scaler

StandardScaler()

In [10]:
scaler.transform(X)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [11]:
test = [[1,7,9]]
scaler.transform(test)

array([[-1.22474487,  0.81649658,  1.22474487]])