<a href="https://colab.research.google.com/github/shubhamByte/Machine-Learning/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# List vs numpy array

In [2]:
import numpy as np
import sys

li_arr = [i for i in range(100)]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

# size difference per item
np_arr.itemsize, sys.getsizeof(li_arr[0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


(8, 24)

Numpy is fast because it supports vectorisation. Vectorisation is a process in which instead of iterating over each element for mathematical opeartion, we do the mathematical opeartion on group of elements(batches) at a single go.

# Creating numpy arrays

1. np.array()


---


2. np.ones()
3. np.zeros()


---


4. np.full()
5. np.empty()


---


6. np.arange()
7. np.linspace()


---


8. np.identity()
9. np.eye()


---


10. np.random.rand()
11. p.random.randint()

In [3]:
a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# dtype value is optional.
a = [1, 2, 3, '4', 4.5]
b = np.array(a, dtype = int)
print(b)

[1 2 3 4 4]


In [5]:
# multiplying with 3 repeats the array three times
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [6]:
# default is float in these type of initialzation, can always use dtype as paramter.
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [7]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [9]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# intialisation with particular element, default is int
b = np.full((3, 3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
# random initialzation
b = np.empty(4)
b

array([1.79925665e-316, 0.00000000e+000, 6.94077320e-310, 6.94077320e-310])

In [12]:
# arange -> step size,   linspace -> no. of elements   (directly provide)

# arange(start, step-size, end(must),...)  , [start, end)
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# [start(must), end(must), no. of elements(default = 0)]      ->  [start, end]

b = np.linspace(2, 10)
b
print(b[1] - b[0])
print(b[3] - b[2])

0.16326530612244916
0.16326530612244916


In [16]:
b = np.linspace(2, 10, 5, dtype = int, endpoint = False)
b

array([2, 3, 5, 6, 8])

In [17]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# can create n * m identity matrix unlike .identity
b = np.eye(3, 4)  
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
# random values between 0 and 1
b = np.random.rand(3)
b

array([0.79888136, 0.79596535, 0.1058204 ])

In [20]:
# between 0 to 10
b = np.random.rand(10)*10
b

array([8.75795241, 6.18246694, 0.93744511, 6.20741926, 2.6671845 ,
       2.34230826, 8.85854927, 2.19367914, 5.67562791, 0.41866746])

In [21]:
b = np.random.rand(2, 3)
b

array([[0.92664601, 0.68360837, 0.40084018],
       [0.4541543 , 0.1322166 , 0.61620106]])

In [22]:
b = np.random.randint(2,3)
b

2

In [23]:
# random.randint(low, high=None, size=None, dtype=int)        -> [start, end)

b = np.random.randint(6, size = 5)
b

array([1, 0, 5, 0, 3])

In [24]:
b = np.random.randint(3, 6, size = (2,3))
b

array([[3, 4, 5],
       [3, 4, 5]])

# Numpy array Properties

### 1D

In [25]:
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [27]:
print(arr.data)
print(arr.dtype)
print(arr.shape)
print(arr.strides)


int64
(5,)
(8,)


### 2D

In [28]:
li_2D = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2D)

print(li_2D)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [29]:
print(arr_2d.data)        # pointer to the first element of the data
print(arr_2d.dtype)
print(arr_2d.shape)
print(arr_2d.strides)     # number of bytes to jump to go to  next row , next item in same row

int64
(4, 4)
(32, 8)


# Slicing and Indexing

In [26]:
li = [1, 2, 3, 4, 5]
arr = np.array(li)

### 1D - Indexing

In [30]:
print(li[3])
print(arr[3])

4
4
[2, 3]
[2 3]


### 1D - Slicing

In [40]:
print(li[1:3])
print(arr[1:3])

# Various omission in slicing
# last index given is excluded
# start omission  = 0, end omission = length of array
print(arr[:3])
print(arr[2:])
print(arr[:])

[2, 3]
[2 3]
[1 2 3]
[3 4 5]
[1 2 3 4 5]




---



In [34]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2D)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 2D - Indexing

In [35]:
print(li_2d[2][3])
print(arr_2d[2][3])

print(arr_2d[2, 3])     # another way to get element using commma, only applicable in numpy array


12
12
12


### 2D - Slicing

In [43]:
# Row not varying
print(li_2d[1][:3])
print(arr_2d[1][:3])

print(arr_2d[1,:3])   # comma variant

[5, 6, 7]
[5 6 7]
[5 6 7]


In [54]:
# Row varying   -> only numpy array can do it properly bcz it has [,] notation for slicing

# here you can understand the subtle difference of meaning in using [][] and [ , ]
# in case of [a][b] -> first a bracket is evaluated and then [b] bracket is evaluated on the result of a bracket.
# but in case of [, ]  -> both are evaluated together and hence proper slicing is done

print(arr_2d[1:4, 2])
print(arr_2d[1:4][2])

print('----------------\n')

print('li_2d[1:4][2]    ->  ', li_2d[1:4][2])

print('li_2d[1:4]       -> ', li_2d[1:4])
print('li_2d[2]         ->  ', li_2d[2])

[ 7 11 15]
[13 14 15 16]
----------------

li_2d[1:4][2]    ->   [13, 14, 15, 16]
li_2d[1:4]       ->  [[5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
li_2d[2]         ->   [9, 10, 11, 12]


In [57]:
# both row and column varying example

print(arr_2d[:2, 1:3])

[[2 3]
 [6 7]]


# Mathematical Operaions